spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${DATABASE:scout_helper}
    username: ${DATABASE_USERNAME:root}
    password: ${DATABASE_PASSWORD:admin}
  security:
    oauth2:
      client:
        registration:
          eve:
            provider: esi
            client-id: ${ESI_CLIENT_ID}
            client-secret: ${ESI_CLIENT_SECRET}
            authorization-grant-type: authorization_code
            redirect-uri: ${ESI_REDIRECT_URL:http://localhost:8080/login/oauth2/code/eve}
            scope:
              - esi-ui.write_waypoint.v1
        provider:
          esi:
            authorization-uri: https://login.eveonline.com/v2/oauth/authorize
            token-uri: https://login.eveonline.com/v2/oauth/token

  jpa:
    open-in-view: false